/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parcialjava;

/**
 *
 * @author Administrador
 */
public class FrmCiudades extends javax.swing.JFrame {

    /**
     * Creates new form FrmCiudades
     */
     String nombre ;
    public FrmCiudades() {
        initComponents();
        
//        txtahorro.setText(Double.toString(0.00));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        BGciudades = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtahorro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnelajiveloz = new javax.swing.JButton();
        btnlosroadrunners = new javax.swing.JButton();
        btnelcoyoteveloz = new javax.swing.JButton();
        btntranportesspedy = new javax.swing.JButton();
        lbEmpresa = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbahorro = new javax.swing.JLabel();
        btnRecet = new javax.swing.JButton();
        rbmexico = new javax.swing.JRadioButton();
        rbacapulco = new javax.swing.JRadioButton();
        rbtanga = new javax.swing.JRadioButton();
        rbcancun = new javax.swing.JRadioButton();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ciudades");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Mexico D.F", "750"},
                {"Acapulco", "800"},
                {"Tangamandapio", "1200"},
                {"Cancun", "2600"}
            },
            new String [] {
                "ciudades", "Distancias(KM)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("DINERO AHORRADO:");

        jLabel2.setText("CIUDAD DESTINO:");

        jLabel3.setText("A DONDE DESEA IR?");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setText("cuidades destinos");

        jLabel5.setText("EMPRESAS");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"El aji veloz", "baño", "$1.3"},
                {"los road runners", "baño, sillas reclinables", "$2.2"},
                {"el coyote veloz", "baño, doble piso, sillas reclinables", "$3.7"},
                {"transportes Speddy gonzales", "baño, doble piso, sillas reclinables, refrigerios, zona VIP, WIFI", "$4.5"}
            },
            new String [] {
                "Empresa", "Servicios", "Costo($/Km)"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel6.setText("QUE EMPRESA DESEA?");

        btnelajiveloz.setText("El aji veloz");
        btnelajiveloz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnelajivelozActionPerformed(evt);
            }
        });

        btnlosroadrunners.setText("Los roadRunners");
        btnlosroadrunners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlosroadrunnersActionPerformed(evt);
            }
        });

        btnelcoyoteveloz.setText("El coyote veloz");
        btnelcoyoteveloz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnelcoyotevelozActionPerformed(evt);
            }
        });

        btntranportesspedy.setText("Transportes Speddy gonzales");
        btntranportesspedy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntranportesspedyActionPerformed(evt);
            }
        });

        lbEmpresa.setText("jLabel8");

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel9.setText("Empresas de Buces");

        btnRecet.setText("recet ");
        btnRecet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecetActionPerformed(evt);
            }
        });

        BGciudades.add(rbmexico);
        rbmexico.setText("Mexico D.F");

        BGciudades.add(rbacapulco);
        rbacapulco.setText("Acapulco");

        BGciudades.add(rbtanga);
        rbtanga.setText("tangamandapio");

        BGciudades.add(rbcancun);
        rbcancun.setText("Cancun");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtahorro, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbahorro))
                                    .addComponent(jLabel3))
                                .addGap(0, 619, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRecet)
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbmexico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbacapulco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtanga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbcancun))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnelajiveloz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnlosroadrunners)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnelcoyoteveloz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btntranportesspedy))
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(338, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addGap(336, 336, 336)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtahorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbahorro))
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbmexico)
                    .addComponent(rbacapulco)
                    .addComponent(rbtanga)
                    .addComponent(rbcancun))
                .addGap(51, 51, 51)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnelajiveloz)
                    .addComponent(btnlosroadrunners)
                    .addComponent(btnelcoyoteveloz)
                    .addComponent(btntranportesspedy))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmpresa)
                    .addComponent(btnRecet))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(267, 267, 267)
                    .addComponent(jLabel9)
                    .addContainerGap(295, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eleccion(){
        if(rbmexico.isSelected()){
            nombre = "Mexico D.F";
        }
        if(rbacapulco.isSelected()){
            nombre = "Acapulco";
        }
        if(rbtanga.isSelected()){
            nombre = "Tangamandapio";
        }
        if(rbcancun.isSelected()){
            nombre = "Cancun";
        }
    }
    
    private void btnRecetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecetActionPerformed
        txtahorro.setText("");
        lbEmpresa.setText("");
        BGciudades.clearSelection();
    }//GEN-LAST:event_btnRecetActionPerformed

    private void btnelajivelozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnelajivelozActionPerformed
          double ahorro, emp1;
    
             eleccion();
            ahorro = Double.parseDouble(txtahorro.getText());
            emp1 = 750*1.3;
            if(ahorro > emp1 ){
               lbEmpresa.setText("usted puede viajar a la ciudad de: "+nombre+" con la Empresa EL AJI VELOZ; Buen viaje");
               }else{
                    lbEmpresa.setText("ahorros insuficientes");
                }
            
    }//GEN-LAST:event_btnelajivelozActionPerformed

    private void btnlosroadrunnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlosroadrunnersActionPerformed
        double ahorro, emp2;
    
             eleccion();
            ahorro = Double.parseDouble(txtahorro.getText());
            emp2 = 800*2.2;
             if(ahorro > emp2 ){
               lbEmpresa.setText("usted puede viajar a la ciudad de: "+nombre+" con la Empresa LOS RadDRunners; Buen viaje");
               }else{
                    lbEmpresa.setText("ahorros insuficientes");
                }
                                                  
    }//GEN-LAST:event_btnlosroadrunnersActionPerformed

    private void btnelcoyotevelozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnelcoyotevelozActionPerformed
         double ahorro, emp3;
             eleccion();
            ahorro = Double.parseDouble(txtahorro.getText());
              emp3 = 1200*3.7;
                if(ahorro > emp3 ){
                lbEmpresa.setText("usted puede viajar a la ciudad de: "+nombre+" con la Empresa El Coyote Veloz; Buen viaje");
            }else{
                    lbEmpresa.setText("ahorros insuficientes");
                }
            
    }//GEN-LAST:event_btnelcoyotevelozActionPerformed

    private void btntranportesspedyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntranportesspedyActionPerformed
           double ahorro, emp4;
             eleccion();
            ahorro = Double.parseDouble(txtahorro.getText());
               emp4 = 2600*4.5;
                if(ahorro > emp4 ){
                lbEmpresa.setText("usted puede viajar a la ciudad de: "+nombre+" con la Empresa Transportes Speedy Gonzalez; Buen viaje");
                }else{
                    lbEmpresa.setText("ahorros insuficientes");
                }
            
    }//GEN-LAST:event_btntranportesspedyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCiudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCiudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCiudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCiudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCiudades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGciudades;
    private javax.swing.JButton btnRecet;
    private javax.swing.JButton btnelajiveloz;
    private javax.swing.JButton btnelcoyoteveloz;
    private javax.swing.JButton btnlosroadrunners;
    private javax.swing.JButton btntranportesspedy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbEmpresa;
    private javax.swing.JLabel lbahorro;
    private javax.swing.JRadioButton rbacapulco;
    private javax.swing.JRadioButton rbcancun;
    private javax.swing.JRadioButton rbmexico;
    private javax.swing.JRadioButton rbtanga;
    private javax.swing.JTextField txtahorro;
    // End of variables declaration//GEN-END:variables
}
